name: Maven CI

# Trigger workflow på push eller pull requests til main branch
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Sjekk ut koden fra repository
    - name: Checkout repository
      uses: actions/checkout@v3

    # Sett opp JDK 21
    - name: Setup JDK 21
      uses: actions/setup-java@v3
      with:
        java-version: '21'
        distribution: 'temurin'

    # Installer avhengigheter og bygg prosjektet
    - name: Install dependencies and build
      run: mvn clean install

    # Kjøre alle JUnit-tester
    - name: Run tests
      run: mvn test
