name: Maven CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Build project
        run: mvn clean compile

      - name: Run tests
        run: mvn test

      - name: Package project
        run: mvn clean package

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: my-java-app
          path: target/*.jar

      - name: Pseudo Deploy
        run: echo "Her kunne vi nå ha deployet *.jar-filen til et staging/produksjonsmiljø."
